services:
  backend:
    image: popebeats2tube-backend
    build:
      context: ./api
    container_name: popebeats-backend
    ports:
      - "4011:4011"
    env_file:
      - ./api/.env.staging
    restart: unless-stopped

  frontend:
    image: popebeats2tube-staging-frontend
    build:
      context: ./frontend
    container_name: popebeats-frontend
    env_file:
      - ./frontend/.env.staging
    ports:
      - "443:443"
    restart: unless-stopped
    volumes:
      - ./certs:/etc/nginx/ssl:ro

