"""add timezone to datetime columns

Revision ID: 343aba6dc949
Revises: 20b8d3935aed
Create Date: 2025-01-07 21:01:56.562839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '343aba6dc949'
down_revision: Union[str, None] = '20b8d3935aed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'date_created',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'date_created',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
